In [1]:
import numpy as np

In [3]:
x = np.zeros(10) #creating a null vector of size till 10 
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#in list the first item has index [0] & after [1],[2],[3] & so on....
x[5] = 1 #putting the value 1 in fifth position
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [15]:
'''arange is a in-built function. 
that used to get evenly spaced values within a given interval.'''
x = np.arange(10,50) #creating a vector range from 10 to 49
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#x.reverse()
#print(x)
#why its showing Object has no attribute 'reverse'
#Reverse() is an method right. then why its showing like that.


In [21]:
revers = x[::-1] #its reverse the vector. The first element becomes last 
print(revers)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [25]:
#in line 15. I already declare what is arange.
#reshape is an function. it means changing the shape of the given array.
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
x = np.array([1,2,0,0,4,0])# creating single dimensional array
print(x)

[1 2 0 0 4 0]


In [37]:
#nonzero is an function that removes 0 from the list/array 
x1 = x[np.nonzero(x)]  
print(x1)

[1 2 4]


In [43]:
x = np.random.random((3,3,3))#creating 3x3x3 array with random values 
print(x)

[[[0.42564606 0.87108984 0.87264931]
  [0.40761359 0.59523878 0.9514577 ]
  [0.23806283 0.28098945 0.95474955]]

 [[0.80254042 0.47303754 0.03892537]
  [0.08754283 0.22808068 0.7423777 ]
  [0.59458689 0.20248958 0.2346279 ]]

 [[0.43552739 0.85426289 0.36071036]
  [0.57829777 0.1227426  0.45044063]
  [0.63039166 0.10095381 0.83038281]]]


In [44]:
x = np.random.random(30)
#mean() is an inbuilt function that used to calculate average of numbers and list.
x2 = x.mean()
print(x2)

0.47187609785662155


In [50]:
#creating 2D array with 5 row & 5 col
x = np.ones((5,5),dtype=int)#dtype=int(its show integer value)
print(x)
#1 on the border and 0 inside in the array
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [49]:
x = np.ones((3,3))
print(x)
x = np.zeros((8,8),dtype=int)
'''Slice from 1st index row till 1+2+2…
fill all columns with 1 starting from 0th to 0+2+2… and so on.'''
x[1::2,::2] = 1
'''Slice from 0th row till 0+2+2…
fill all columns with 1 starting from 1 to 1+2+2+'''
x[::2,1::2] = 1
print(x)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
# What is the major difference between sets, lists, tuples and dict?
#set = A set is an unordered collection.{mutable, dont have duplicate elements.}
#list = A list is a collection of ordered data.[mutable]
#tuple = A tuple is an ordered collection of data.(immutable)
#dict = A dictionary is an unordered collection of data.{mutable, not allow duplicates}

In [53]:
#printing 1 to 10 num using while loop 
num = 1
while(num<=10):
    print(num)
    num+= 1

1
2
3
4
5
6
7
8
9
10


In [56]:
start, end = -10, -1 #starting from -10 and ends to -1 
# iterating each number in list
for num in range(start, end + 1):
    print(num, end = " ")

-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

In [57]:
#printing the message "Done" after executing.
for i in range(5):
    print(i)
else:
    print('Done!:)')

0
1
2
3
4
Done!:)


In [58]:
x = np.random.random(10)
print(x)
x.sort()# sorting means arranging the value.
print(x)

[0.67327078 0.97392421 0.41640483 0.0872179  0.4780015  0.2858019
 0.40103704 0.94470738 0.97533287 0.48368923]
[0.0872179  0.2858019  0.40103704 0.41640483 0.4780015  0.48368923
 0.67327078 0.94470738 0.97392421 0.97533287]


In [63]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
